// server/api/horizon/check.post.ts
// Uses pre-computed horizon grid (generated by scripts/precompute-horizon-grid.ts)
// so the 856MB DEM binary is not needed at runtime.
import { readFileSync } from 'node:fs'
import { resolve, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'
import type { HorizonCheckResponse, HorizonSweepPoint } from '~/types/horizon'

// Compact grid point format from precompute script
interface GridPoint {
  lat: number; lng: number
  v: string; c: number; mh: number; oe: number
  sa: number; sz: number
  bd: number | null; be: number | null
  td: number | null
  s: [number, number, number][] // [azimuth, horizon_angle, distance_m]
}

interface HorizonGrid {
  point_count: number
  points: GridPoint[]
}

// Cache grid in module scope; shared promise prevents duplicate loads on cold start
let gridCache: HorizonGrid | null = null
let gridLoadPromise: Promise<HorizonGrid> | null = null

function loadGridFromFS(): HorizonGrid | null {
  const candidates = [
    resolve(process.cwd(), 'public', 'eclipse-data', 'horizon-grid.json'),
    resolve(process.cwd(), '.output', 'public', 'eclipse-data', 'horizon-grid.json'),
  ]

  try {
    const currentDir = dirname(fileURLToPath(import.meta.url))
    candidates.push(resolve(currentDir, '..', '..', 'public', 'eclipse-data', 'horizon-grid.json'))
    candidates.push(resolve(currentDir, '..', '..', '..', 'public', 'eclipse-data', 'horizon-grid.json'))
  } catch { /* import.meta.url may not resolve in all envs */ }

  for (const path of candidates) {
    try {
      const grid = JSON.parse(readFileSync(path, 'utf-8')) as HorizonGrid
      console.log(`[Horizon] Loaded grid from filesystem: ${path} (${grid.point_count} points)`)
      return grid
    } catch { /* try next */ }
  }
  return null
}

async function loadGridAsync(): Promise<HorizonGrid> {
  // Try filesystem first (works in local dev)
  const fromFS = loadGridFromFS()
  if (fromFS) return fromFS

  // Fallback: use Nitro's serverAssets storage (works on Vercel if assets are bundled)
  try {
    const data = await useStorage('assets:server:eclipse-data').getItem('horizon-grid.json')
    if (data) {
      const grid = (typeof data === 'string' ? JSON.parse(data) : data) as HorizonGrid
      console.log(`[Horizon] Loaded grid via Nitro storage (${grid.point_count} points)`)
      return grid
    }
  } catch (e: any) {
    console.warn('[Horizon] Nitro storage fallback failed:', e.message)
  }

  // Last resort: fetch from own public URL (static assets are on CDN)
  try {
    const config = useRuntimeConfig()
    const baseUrl = config.public.siteUrl
      || (process.env.VERCEL_URL ? `https://${process.env.VERCEL_URL}` : '')
      || 'http://localhost:3000'
    const url = `${baseUrl}/eclipse-data/horizon-grid.json`
    console.log(`[Horizon] Attempting HTTP fetch from ${url}`)
    const res = await fetch(url)
    if (res.ok) {
      const grid = await res.json() as HorizonGrid
      console.log(`[Horizon] Loaded grid via HTTP (${grid.point_count} points)`)
      return grid
    }
    console.error(`[Horizon] HTTP fetch failed with status ${res.status}`)
  } catch (e: any) {
    console.error('[Horizon] HTTP fallback failed:', e.message)
  }

  throw new Error('horizon-grid.json not found via filesystem, storage, or HTTP')
}

function loadGrid(): Promise<HorizonGrid> {
  if (gridCache) return Promise.resolve(gridCache)
  // Share a single promise across concurrent cold-start requests
  if (!gridLoadPromise) {
    gridLoadPromise = loadGridAsync().then((grid) => {
      gridCache = grid
      return grid
    }).catch((e) => {
      gridLoadPromise = null // allow retry on failure
      throw e
    })
  }
  return gridLoadPromise
}

// Max snap distance in degrees (~3km at 65°N)
const MAX_SNAP_DIST_DEG = 0.035

export default defineEventHandler(async (event) => {
  // Rate limit: 10 req/min per IP
  const rawIp = getHeader(event, 'x-forwarded-for') || getHeader(event, 'x-real-ip') || 'unknown'
  const ip = rawIp.split(',')[0]!.trim()
  if (!checkRateLimit(`horizon:${ip}`, 10, 60_000)) {
    throw createError({ statusCode: 429, message: 'Too many requests, try again in a minute' })
  }

  // Parse body
  const body = await readBody<{ lat: number; lng: number }>(event)
  if (body?.lat == null || body?.lng == null || typeof body.lat !== 'number' || typeof body.lng !== 'number') {
    throw createError({ statusCode: 400, message: 'lat and lng are required numbers' })
  }

  // Load pre-computed grid
  let grid: HorizonGrid
  try {
    grid = await loadGrid()
  } catch (e) {
    console.error('[Horizon] Failed to load grid:', e)
    throw createError({ statusCode: 503, message: 'Horizon data not available' })
  }

  // Find nearest grid point
  let nearest: GridPoint | null = null
  let minDist = Infinity
  for (const gp of grid.points) {
    const d = (body.lat - gp.lat) ** 2 + (body.lng - gp.lng) ** 2
    if (d < minDist) { minDist = d; nearest = gp }
  }

  if (!nearest || Math.sqrt(minDist) > MAX_SNAP_DIST_DEG) {
    throw createError({ statusCode: 422, message: 'Location outside coverage area' })
  }

  // Expand compact format to full HorizonCheckResponse
  const sweep: HorizonSweepPoint[] = nearest.s.map(([azimuth, horizon_angle, distance_m]) => ({
    azimuth, horizon_angle, distance_m,
  }))

  const peakfinderUrl = `https://www.peakfinder.com/?lat=${body.lat}&lng=${body.lng}&name=Custom%20Location&ele=${Math.round(nearest.oe)}&azi=${Math.round(nearest.sz)}`

  const response: HorizonCheckResponse = {
    verdict: nearest.v as HorizonCheckResponse['verdict'],
    clearance_degrees: nearest.c,
    max_horizon_angle: nearest.mh,
    blocking_distance_m: nearest.bd,
    blocking_elevation_m: nearest.be,
    observer_elevation_m: nearest.oe,
    sun_altitude: nearest.sa,
    sun_azimuth: nearest.sz,
    checked_at: new Date().toISOString(),
    sweep,
    peakfinder_url: peakfinderUrl,
    totality_duration_seconds: nearest.td,
    in_totality_path: nearest.td != null && nearest.td > 0,
  }

  return response
})
