// server/api/horizon/check.post.ts
// Uses pre-computed horizon grid (generated by scripts/precompute-horizon-grid.ts)
// so the 856MB DEM binary is not needed at runtime.
import { readFileSync } from 'node:fs'
import { resolve, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'
import type { HorizonCheckResponse, HorizonSweepPoint } from '~/types/horizon'

// Rate limiting: 10 req/min per IP, with eviction to prevent memory leak
const rateLimits = new Map<string, { count: number; resetAt: number }>()

function checkRateLimit(ip: string): boolean {
  const now = Date.now()
  const entry = rateLimits.get(ip)
  if (!entry || now > entry.resetAt) {
    if (rateLimits.size > 1000) {
      for (const [k, v] of rateLimits) {
        if (now > v.resetAt) rateLimits.delete(k)
      }
    }
    rateLimits.set(ip, { count: 1, resetAt: now + 60_000 })
    return true
  }
  entry.count++
  return entry.count <= 10
}

// Compact grid point format from precompute script
interface GridPoint {
  lat: number; lng: number
  v: string; c: number; mh: number; oe: number
  sa: number; sz: number
  bd: number | null; be: number | null
  td: number | null
  s: [number, number, number][] // [azimuth, horizon_angle, distance_m]
}

interface HorizonGrid {
  point_count: number
  points: GridPoint[]
}

// Cache grid in module scope
let gridCache: HorizonGrid | null = null

function loadGrid(): HorizonGrid {
  if (gridCache) return gridCache

  // Try multiple paths to find the grid file (works on local dev + Vercel)
  const candidates = [
    resolve(process.cwd(), 'public', 'eclipse-data', 'horizon-grid.json'),
    resolve(process.cwd(), '.output', 'public', 'eclipse-data', 'horizon-grid.json'),
  ]

  // On Vercel, __dirname resolves relative to the serverless function bundle
  try {
    const currentDir = dirname(fileURLToPath(import.meta.url))
    candidates.push(resolve(currentDir, '..', '..', 'public', 'eclipse-data', 'horizon-grid.json'))
    candidates.push(resolve(currentDir, '..', '..', '..', 'public', 'eclipse-data', 'horizon-grid.json'))
  } catch { /* import.meta.url may not resolve in all envs */ }

  for (const path of candidates) {
    try {
      gridCache = JSON.parse(readFileSync(path, 'utf-8')) as HorizonGrid
      console.log(`[Horizon] Loaded pre-computed grid from ${path}: ${gridCache.point_count} points`)
      return gridCache
    } catch { /* try next */ }
  }

  throw new Error('horizon-grid.json not found in any candidate path')
}

// Max snap distance in degrees (~3km at 65°N)
const MAX_SNAP_DIST_DEG = 0.035

export default defineEventHandler(async (event) => {
  // Rate limit
  const rawIp = getHeader(event, 'x-forwarded-for') || getHeader(event, 'x-real-ip') || 'unknown'
  const ip = rawIp.split(',')[0]!.trim()
  if (!checkRateLimit(ip)) {
    throw createError({ statusCode: 429, message: 'Too many requests, try again in a minute' })
  }

  // Parse body
  const body = await readBody<{ lat: number; lng: number }>(event)
  if (body?.lat == null || body?.lng == null || typeof body.lat !== 'number' || typeof body.lng !== 'number') {
    throw createError({ statusCode: 400, message: 'lat and lng are required numbers' })
  }

  // Load pre-computed grid
  let grid: HorizonGrid
  try {
    grid = loadGrid()
  } catch (e) {
    console.error('[Horizon] Failed to load grid:', e)
    throw createError({ statusCode: 503, message: 'Horizon data not available' })
  }

  // Find nearest grid point
  let nearest: GridPoint | null = null
  let minDist = Infinity
  for (const gp of grid.points) {
    const d = (body.lat - gp.lat) ** 2 + (body.lng - gp.lng) ** 2
    if (d < minDist) { minDist = d; nearest = gp }
  }

  if (!nearest || Math.sqrt(minDist) > MAX_SNAP_DIST_DEG) {
    throw createError({ statusCode: 422, message: 'Location outside coverage area' })
  }

  // Expand compact format to full HorizonCheckResponse
  const sweep: HorizonSweepPoint[] = nearest.s.map(([azimuth, horizon_angle, distance_m]) => ({
    azimuth, horizon_angle, distance_m,
  }))

  const peakfinderUrl = `https://www.peakfinder.com/?lat=${body.lat}&lng=${body.lng}&name=Custom%20Location&ele=${Math.round(nearest.oe)}&azi=${Math.round(nearest.sz)}`

  const response: HorizonCheckResponse = {
    verdict: nearest.v as HorizonCheckResponse['verdict'],
    clearance_degrees: nearest.c,
    max_horizon_angle: nearest.mh,
    blocking_distance_m: nearest.bd,
    blocking_elevation_m: nearest.be,
    observer_elevation_m: nearest.oe,
    sun_altitude: nearest.sa,
    sun_azimuth: nearest.sz,
    checked_at: new Date().toISOString(),
    sweep,
    peakfinder_url: peakfinderUrl,
    totality_duration_seconds: nearest.td,
    in_totality_path: nearest.td != null && nearest.td > 0,
  }

  return response
})
