-- Skyfield-derived totality_duration_seconds + totality_start for every
-- spot where the stored value drifts more than 2s (duration) or 10s (start)
-- from the Skyfield truth at the spot's exact coordinates.
--
-- Why this migration exists: prior duration values were bilinear-interpolated
-- from public/eclipse-data/grid.json, which until now snapped totality bounds
-- to 5s sample boundaries (compute-eclipse-grid.py undersamples C2/C3). The
-- script has been fixed to bisect C2/C3 to 1s like C1/C4; grid.json will be
-- regenerated separately. This migration patches the spots table directly so
-- the /spots/[slug] Sky and Plan tabs reflect reality.
--
-- Start times were also adjusted: many were hand-set during the initial seed
-- and drifted up to ~60s from Skyfield C2 at the exact coords.
--
-- Generated by scripts/internal/gen-spot-skyfield-migration.py.
-- Sun alt/az NOT modified — migrations 013/014/015 set them within 0.07 deg
-- of Skyfield already.

-- arnarstapi-coastal-platform: dur 119->125 (-5.7s)
UPDATE viewing_spots SET totality_duration_seconds = 125 WHERE slug = 'arnarstapi-coastal-platform';

-- blue-lagoon: dur 96->99 (-3.1s); start drift +43s
UPDATE viewing_spots SET totality_duration_seconds = 99, totality_start = '2026-08-12T17:48:22Z' WHERE slug = 'blue-lagoon';

-- breidavik-beach: dur 126->130 (-4.3s); start drift +57s
UPDATE viewing_spots SET totality_duration_seconds = 130, totality_start = '2026-08-12T17:44:28Z' WHERE slug = 'breidavik-beach';

-- budir-black-church: dur 113->117 (-3.6s)
UPDATE viewing_spots SET totality_duration_seconds = 117 WHERE slug = 'budir-black-church';

-- djupalonssandur-beach: dur 125->130 (-4.7s)
UPDATE viewing_spots SET totality_duration_seconds = 130 WHERE slug = 'djupalonssandur-beach';

-- gardur-lighthouse: dur 100->104 (-4.1s); start drift -17s
UPDATE viewing_spots SET totality_duration_seconds = 104, totality_start = '2026-08-12T17:47:52Z' WHERE slug = 'gardur-lighthouse';

-- grotta-lighthouse-reykjavik: dur 63->67 (-3.6s); start drift -42s
UPDATE viewing_spots SET totality_duration_seconds = 67, totality_start = '2026-08-12T17:48:12Z' WHERE slug = 'grotta-lighthouse-reykjavik';

-- haestahjallafoss-dynjandi: dur 95->100 (-4.7s)
UPDATE viewing_spots SET totality_duration_seconds = 100 WHERE slug = 'haestahjallafoss-dynjandi';

-- hellissandur-village: dur 123->128 (-4.8s)
UPDATE viewing_spots SET totality_duration_seconds = 128 WHERE slug = 'hellissandur-village';

-- hellnar-viewpoint: dur 119->124 (-5.1s)
UPDATE viewing_spots SET totality_duration_seconds = 124 WHERE slug = 'hellnar-viewpoint';

-- hvalsneskirkja: dur 100->108 (-7.8s)
UPDATE viewing_spots SET totality_duration_seconds = 108 WHERE slug = 'hvalsneskirkja';

-- isafjordur-harbour: start drift +22s
UPDATE viewing_spots SET totality_start = '2026-08-12T17:44:08Z' WHERE slug = 'isafjordur-harbour';

-- keflavik-asbru-viewpoint: dur 99->102 (-2.6s); start drift -32s
UPDATE viewing_spots SET totality_duration_seconds = 102, totality_start = '2026-08-12T17:48:07Z' WHERE slug = 'keflavik-asbru-viewpoint';

-- kirkjufell-viewpoint: dur 100->114 (-14.1s); start drift +18s
UPDATE viewing_spots SET totality_duration_seconds = 114, totality_start = '2026-08-12T17:46:02Z' WHERE slug = 'kirkjufell-viewpoint';

-- latrabjarg-cliffs: dur 130->133 (-3.4s); start drift +50s
UPDATE viewing_spots SET totality_duration_seconds = 133, totality_start = '2026-08-12T17:44:30Z' WHERE slug = 'latrabjarg-cliffs';

-- londrangar-malarrif: dur 121->127 (-6.2s)
UPDATE viewing_spots SET totality_duration_seconds = 127 WHERE slug = 'londrangar-malarrif';

-- olafsvik-harbour: dur 118->125 (-7.3s)
UPDATE viewing_spots SET totality_duration_seconds = 125 WHERE slug = 'olafsvik-harbour';

-- patreksfjordur-beach: dur 118->123 (-5.4s); start drift +47s
UPDATE viewing_spots SET totality_duration_seconds = 123, totality_start = '2026-08-12T17:44:33Z' WHERE slug = 'patreksfjordur-beach';

-- perlan-reykjavik: dur 56->60 (-4.3s)
UPDATE viewing_spots SET totality_duration_seconds = 60 WHERE slug = 'perlan-reykjavik';

-- reykjanesta-lighthouse: dur 99->108 (-9.4s); start drift -40s
UPDATE viewing_spots SET totality_duration_seconds = 108, totality_start = '2026-08-12T17:48:20Z' WHERE slug = 'reykjanesta-lighthouse';

-- rif-harbour-snaefellsnes: dur 121->126 (-4.9s); start drift +10s
UPDATE viewing_spots SET totality_duration_seconds = 126, totality_start = '2026-08-12T17:45:50Z' WHERE slug = 'rif-harbour-snaefellsnes';

-- sandafell-thingeyri: dur 100->110 (-9.7s)
UPDATE viewing_spots SET totality_duration_seconds = 110 WHERE slug = 'sandafell-thingeyri';

-- saxholl-crater: dur 115->129 (-14.1s)
UPDATE viewing_spots SET totality_duration_seconds = 129 WHERE slug = 'saxholl-crater';

-- sky-lagoon: dur 63->66 (-2.9s)
UPDATE viewing_spots SET totality_duration_seconds = 66 WHERE slug = 'sky-lagoon';

-- snaefellsjokull-summit: dur 121->128 (-6.8s)
UPDATE viewing_spots SET totality_duration_seconds = 128 WHERE slug = 'snaefellsjokull-summit';

-- stykkisholmur-harbour-hill: dur 84->88 (-4.4s); start drift +12s
UPDATE viewing_spots SET totality_duration_seconds = 88, totality_start = '2026-08-12T17:46:08Z' WHERE slug = 'stykkisholmur-harbour-hill';

-- svodufoss-waterfall: dur 116->122 (-6.2s)
UPDATE viewing_spots SET totality_duration_seconds = 122 WHERE slug = 'svodufoss-waterfall';

-- ytri-tunga-beach: dur 105->108 (-2.8s)
UPDATE viewing_spots SET totality_duration_seconds = 108 WHERE slug = 'ytri-tunga-beach';
