-- Add per-spot C1 (partial begins) and C4 (partial ends) to viewing_spots,
-- populated from Skyfield at each spot's exact coordinates (1s precision).
--
-- Why this exists: previously C1/C4 were enriched at request time in
-- server/api/spots/[slug].get.ts via nearestGridPoint() against
-- public/eclipse-data/grid.json. With ~0.15deg grid step the nearest
-- point can be 5-10 km from the spot, giving C1/C4 drift of several
-- seconds. Storing per-spot values removes that drift entirely.
--
-- Generated by scripts/internal/gen-c1-c4-migration.mjs from
-- scripts/internal/skyfield-contacts.json (built by
-- scripts/internal/skyfield-contacts-all-spots.py). Re-run both to
-- refresh after adding/moving spots.

ALTER TABLE viewing_spots
  ADD COLUMN IF NOT EXISTS c1 TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS c4 TIMESTAMPTZ;

UPDATE viewing_spots SET c1 = '2026-08-12T16:46:53Z', c4 = '2026-08-12T18:45:24Z' WHERE slug = 'akranes-lighthouse';
UPDATE viewing_spots SET c1 = '2026-08-12T16:45:24Z', c4 = '2026-08-12T18:44:39Z' WHERE slug = 'arnarstapi-coastal-platform';
UPDATE viewing_spots SET c1 = '2026-08-12T16:47:30Z', c4 = '2026-08-12T18:46:24Z' WHERE slug = 'blue-lagoon';
UPDATE viewing_spots SET c1 = '2026-08-12T16:43:42Z', c4 = '2026-08-12T18:43:01Z' WHERE slug = 'breidavik-beach';
UPDATE viewing_spots SET c1 = '2026-08-12T16:45:25Z', c4 = '2026-08-12T18:44:31Z' WHERE slug = 'budir-black-church';
UPDATE viewing_spots SET c1 = '2026-08-12T16:45:18Z', c4 = '2026-08-12T18:44:39Z' WHERE slug = 'djupalonssandur-beach';
UPDATE viewing_spots SET c1 = '2026-08-12T16:47:02Z', c4 = '2026-08-12T18:45:59Z' WHERE slug = 'gardur-lighthouse';
UPDATE viewing_spots SET c1 = '2026-08-12T16:47:11Z', c4 = '2026-08-12T18:45:41Z' WHERE slug = 'grotta-lighthouse-reykjavik';
UPDATE viewing_spots SET c1 = '2026-08-12T16:43:54Z', c4 = '2026-08-12T18:42:44Z' WHERE slug = 'haestahjallafoss-dynjandi';
UPDATE viewing_spots SET c1 = '2026-08-12T16:45:01Z', c4 = '2026-08-12T18:44:19Z' WHERE slug = 'hellissandur-village';
UPDATE viewing_spots SET c1 = '2026-08-12T16:45:25Z', c4 = '2026-08-12T18:44:39Z' WHERE slug = 'hellnar-viewpoint';
UPDATE viewing_spots SET c1 = '2026-08-12T16:47:11Z', c4 = '2026-08-12T18:46:11Z' WHERE slug = 'hvalsneskirkja';
UPDATE viewing_spots SET c1 = '2026-08-12T16:43:20Z', c4 = '2026-08-12T18:42:04Z' WHERE slug = 'isafjordur-harbour';
UPDATE viewing_spots SET c1 = '2026-08-12T16:47:16Z', c4 = '2026-08-12T18:46:11Z' WHERE slug = 'keflavik-asbru-viewpoint';
UPDATE viewing_spots SET c1 = '2026-08-12T16:45:14Z', c4 = '2026-08-12T18:44:19Z' WHERE slug = 'kirkjufell-viewpoint';
UPDATE viewing_spots SET c1 = '2026-08-12T16:43:43Z', c4 = '2026-08-12T18:43:06Z' WHERE slug = 'latrabjarg-cliffs';
UPDATE viewing_spots SET c1 = '2026-08-12T16:45:24Z', c4 = '2026-08-12T18:44:41Z' WHERE slug = 'londrangar-malarrif';
UPDATE viewing_spots SET c1 = '2026-08-12T16:45:09Z', c4 = '2026-08-12T18:44:24Z' WHERE slug = 'olafsvik-harbour';
UPDATE viewing_spots SET c1 = '2026-08-12T16:45:01Z', c4 = '2026-08-12T18:44:21Z' WHERE slug = 'ondverdarnes-svortuloft';
UPDATE viewing_spots SET c1 = '2026-08-12T16:43:48Z', c4 = '2026-08-12T18:42:59Z' WHERE slug = 'patreksfjordur-beach';
UPDATE viewing_spots SET c1 = '2026-08-12T16:47:18Z', c4 = '2026-08-12T18:45:44Z' WHERE slug = 'perlan-reykjavik';
UPDATE viewing_spots SET c1 = '2026-08-12T16:47:30Z', c4 = '2026-08-12T18:46:31Z' WHERE slug = 'reykjanesta-lighthouse';
UPDATE viewing_spots SET c1 = '2026-08-12T16:45:03Z', c4 = '2026-08-12T18:44:19Z' WHERE slug = 'rif-harbour-snaefellsnes';
UPDATE viewing_spots SET c1 = '2026-08-12T16:43:31Z', c4 = '2026-08-12T18:42:29Z' WHERE slug = 'sandafell-thingeyri';
UPDATE viewing_spots SET c1 = '2026-08-12T16:45:07Z', c4 = '2026-08-12T18:44:26Z' WHERE slug = 'saxholl-crater';
UPDATE viewing_spots SET c1 = '2026-08-12T16:47:17Z', c4 = '2026-08-12T18:45:46Z' WHERE slug = 'sky-lagoon';
UPDATE viewing_spots SET c1 = '2026-08-12T16:45:16Z', c4 = '2026-08-12T18:44:34Z' WHERE slug = 'snaefellsjokull-summit';
UPDATE viewing_spots SET c1 = '2026-08-12T16:45:15Z', c4 = '2026-08-12T18:43:59Z' WHERE slug = 'stykkisholmur-harbour-hill';
UPDATE viewing_spots SET c1 = '2026-08-12T16:45:15Z', c4 = '2026-08-12T18:44:26Z' WHERE slug = 'svodufoss-waterfall';
UPDATE viewing_spots SET c1 = '2026-08-12T16:45:35Z', c4 = '2026-08-12T18:44:34Z' WHERE slug = 'ytri-tunga-beach';
