-- Icelandic translations for curated viewing spots.
--
-- Run AFTER migration 008-spot-translations.sql.
-- Re-running this script is safe — it acts as an upsert via
-- ON CONFLICT (spot_slug, locale) DO UPDATE.
--
-- Skips-missing-FK pattern: this script bundles every Icelandic
-- translation row into a single INSERT … SELECT … WHERE EXISTS, so
-- any row whose spot doesn't exist in viewing_spots is silently
-- dropped instead of throwing an FK violation. Safe to run on a
-- partially-seeded environment.
--
-- THIS FILE IS GENERATED by scripts/internal/generate-spot-translations-is.mjs
-- from raw-photos/parsed-spots.json (which is parsed from the latest
-- production INSERT in raw-photos/viewing_spots_rows.sql). To refresh:
--   1. Export viewing_spots from Supabase → raw-photos/viewing_spots_rows.sql
--   2. node scripts/internal/parse-spots.mjs       (regenerates parsed-spots.json)
--   3. node scripts/internal/generate-spot-translations-is.mjs
-- Don't hand-edit this file directly — edit the generator's IS map.
--
-- Coverage: 28 spots, matching production exactly.
-- Translation notes:
--   • Icelandic place names are kept (Snæfellsjökull, Vestfirðir,
--     Reykjavík, Reykjanesskagi, Borgarfjörður).
--   • Eclipse vocabulary follows established Icelandic usage:
--     heilmyrkvi (totality), heilsólmyrkvi (total eclipse),
--     deildarmyrkvi (partial), kóróna, sjóndeildarhringur, sólhæð.
--   • Translations are machine-quality but follow native idiom
--     where possible. Recommend a native review pass before launch
--     for the longer paragraphs.

WITH translations(spot_slug, locale, name, description, parking_info, terrain_notes, warnings) AS (
  VALUES
    (
      'akranes-lighthouse', 'is',
      'Akranesviti',
      'Bær á tanga Akranesskagans með vita sem býður 270° útsýni yfir hafið. Vesturströndin er með algjörlega opinn sjóndeildarhring. Stutt heilmyrkvi (nálægt suðurjaðri leiðarinnar) en frábært aðgengi — aðeins 45 mínútna akstur frá Reykjavík um Hvalfjarðargöng.',
      'Frí bílastæði nálægt vitanum og meðfram strandgötunni.',
      'Slétt strandsvæði nálægt vitanum. Malbikaðir stígar og malarströnd.',
      '[{"level":"info","title":"Aðeins ~1 mínúta heilmyrkvi — en mjög aðgengilegt (45 mín frá Reykjavík um Hvalfjarðargöng)","body":""},{"level":"info","title":"Bærinn býr yfir fullri þjónustu — veitingastöðum, matvöruverslun og sundlaug","body":""}]'::jsonb
    ),
    (
      'arnarstapi-coastal-platform', 'is',
      'Arnarstapi — strandstöpullinn',
      'Stórbrotið strandþorp við rætur Snæfellsjökuls. Sléttur hraunpallur sem teygir sig út í hafið býður upp á víðopinn vestursjóndeildarhring. Hinn frægi sjávarbogi Gatklettur og svartir basaltdrangar mynda dramatíska umgjörð fyrir sólmyrkvann.',
      'Afmörkuð malarbílastæði við upphaf strandgöngustígsins. Frítt, ~60–80 bílar.',
      'Sléttur til bylgjóttur hraunpallur. Sumstaðar grýtt undirlag nálægt klettum.',
      '[{"level":"warn","title":"Vinsæll ferðamannastaður — búast má við miklu fjölmenni á sólmyrkvadegi","body":""},{"level":"bad","title":"Klettabrúnir meðfram strandstígnum eru ógirtar — gættu að börnum og stígðu varlega","body":""},{"level":"warn","title":"Bílastæði eru takmörkuð — íhugaðu að mæta vel fyrir sólmyrkvann","body":""}]'::jsonb
    ),
    (
      'blue-lagoon', 'is',
      'Bláa lónið',
      'Frægasti ferðamannastaður Íslands — jarðhitaspaa í svörtu hraunbreiðu á Reykjanesskaga. Í fyrsta sinn í sögu sinni liggur Bláa lónið beint á leið heilmyrkvans. Gestir geta upplifað sólmyrkvann úr hlýju, steinefnaríku vatninu með óhindruðu vestur-suðvestur útsýni yfir hraunbreiðuna.',
      'Stórt bílastæði með pláss fyrir hundruð bíla. Vel skipulagt komu- og brottfararkerfi.',
      'Slétt hraunbreiða í um 30 m hæð. Ekkert verulegt landslag í kring. Opinn himinn í allar áttir.',
      '[{"level":"info","title":"MIÐAR NAUÐSYNLEGIR — Bláa lónið krefst fyrirframbókaðrar aðgöngu","body":""},{"level":"info","title":"Sérstakir sólmyrkvamiðar seljast hratt — bókaðu strax","body":""},{"level":"info","title":"Útsýni yfir sólmyrkvann getur verið takmarkað af spaa-byggingum (gufu, húsum) eftir staðsetningu í lóninu","body":""},{"level":"info","title":"Verðlag er hátt (forgangsverð fyrir sólmyrkvaviðburðinn)","body":""}]'::jsonb
    ),
    (
      'breidavik-beach', 'is',
      'Breiðavíkurströnd',
      'Stórkostleg gulleit sandströnd nálægt Látrabjargi sem snýr í vestur að opnu Atlantshafi. Einn af þeim stöðum á meginlandinu sem liggur næst miðlínu sólmyrkvans. Algjörlega opinn vestursjóndeildarhringur. Engin þjónusta — afskekktur staður sem krefst undirbúnings, en býður á móti einhvers besta sólmyrkvaútsýnis á Íslandi.',
      'Lítið malarbílastæði við ströndina. Frítt.',
      'Gulleit sandströnd, slétt og opin. Útsett fyrir Atlantshafsvindum.',
      '[{"level":"warn","title":"Afskekkt: 2 klst akstur frá Patreksfirði um malarvegi að hluta","body":""},{"level":"warn","title":"Eina þjónustan er Hótel Breiðavík — bókaðu gistingu með góðum fyrirvara","body":""},{"level":"warn","title":"Ekkert farsímasamband — sæktu ónettengd kort fyrir komu","body":""},{"level":"info","title":"Útsett fyrir Atlantshafsvindum — klæddu þig hlýlega","body":""}]'::jsonb
    ),
    (
      'budir-black-church', 'is',
      'Búðakirkja (svarta kirkjan)',
      'Hin táknræna svarta timburkirkja á Búðum stendur á opinni hraunbreiðu með víðu útsýni til vesturs yfir Faxaflóa. Andstæða svörtu kirkjunnar við myrkan sólmyrkvahimininn gerir þennan stað að einum mest myndræna sólmyrkvasjónarhornanna á Íslandi.',
      'Bílastæði við Hótel Búðir og nálægt kirkjunni. Frítt.',
      'Opin hraunbreiða með mosa á yfirborði. Sléttur jarðvegur umhverfis kirkjuna.',
      '[{"level":"info","title":"Bílastæði Hótels Búða eru fyrir hótelgesti — leggðu meðfram veginum ef stæðið er fullt","body":""},{"level":"info","title":"Búðakirkja er starfandi kirkja — sýndu virðingu ef messur fara fram","body":""},{"level":"warn","title":"Takmörkuð bílastæði (~20 bílar) — mættu snemma á sólmyrkvadegi","body":""}]'::jsonb
    ),
    (
      'djupalonssandur-beach', 'is',
      'Djúpalónssandur',
      'Svört hraunsteinsströnd á vesturodda Snæfellsness, innan þjóðgarðs Snæfellsjökuls. Stutt ganga frá bílastæði í gegnum hraunmyndanir niður á dramatíska ströndina. Snýr beint í vestur — fullkomið fyrir sólmyrkvann. Ein helsta sólmyrkvaperla Snæfellsness.',
      'Malbikað bílastæði við upphaf gönguleiðarinnar. Frítt, salerni á staðnum.',
      'Malarstígur í gegnum hraunmyndanir, mild halli niður á ströndina. Sumstaðar ójafnt undirlag.',
      '[{"level":"warn","title":"Innan þjóðgarðs Snæfellsjökuls — búast má við miklu fjölmenni á sólmyrkvadegi","body":""},{"level":"info","title":"Engin þjónusta á ströndinni — salerni eingöngu á bílastæðinu","body":""},{"level":"info","title":"Stutt en grýtt ganga niður á ströndina — farðu í góðum gönguskóm","body":""},{"level":"info","title":"Strandyfirborðið er svört smásteinaströnd, ekki sandur — taktu með stól eða ábreiðu","body":""}]'::jsonb
    ),
    (
      'gardur-lighthouse', 'is',
      'Garðskagaviti',
      'Á nyrsta odda Reykjanesskagans bjóða Garðskagavitinn 270° hafsýn. Tveir vitar (sá gamli frá 1897 og sá nýi) standa á sléttri tá með algjörlega opnum sjóndeildarhring. Frábær eldsneytisstöð fyrir sólmyrkvachasers nálægt Keflavíkurflugvelli, með nokkuð langan heilmyrkva fyrir Reykjanes (~1m 35s).',
      'Frí bílastæði nálægt báðum vitunum. Malbikað stæði.',
      'Slétt strandtáh með malbikuðum stígum milli vitanna. Opin og útsett fyrir vindi.',
      '[{"level":"warn","title":"Mjög vindasamur strandoddi — festu búnað og klæddu þig í vindheldar flíkur","body":""},{"level":"warn","title":"Vinsæll vegna nálægðar við Keflavíkurflugvöll — búast má við fjölmenni","body":""},{"level":"warn","title":"Besti sólmyrkvastaðurinn á Reykjanesi — bílastæði (~40 bílar) gætu fyllst á sólmyrkvadegi","body":""}]'::jsonb
    ),
    (
      'grotta-lighthouse-reykjavik', 'is',
      'Gróttuviti',
      'Sjávarhólmi á vesturodda Seltjarnarness í Reykjavík. Opin hafsýn til vesturs án ljósmengunar eða bygginga á sjóndeildarhringnum. Besti sólmyrkvastaður á Reykjavíkursvæðinu, en heilmyrkvinn endist aðeins um 1 mín 6 sek.',
      'Frí bílastæði við inngang Gróttu náttúrufriðlands. ~30 stæði, 5 mínútna ganga að vitanum.',
      'Slétt eldfjallaberg og malarströnd. Sjávarfallaslóð getur verið undir vatni — athugaðu sjávarfallatöflu fyrir 12. ágúst.',
      '[{"level":"warn","title":"Verður EXTREMELY fjölmennt — hugsanlega þúsundir manna af öllu höfuðborgarsvæðinu","body":""},{"level":"bad","title":"Vegurinn út í vitaeyjuna er EINGÖNGU aðgengilegur við fjöru — athugaðu sjávarfallatöflu fyrir 12. ágúst","body":""},{"level":"warn","title":"Bílastæði fyllast mjög snemma — íhugaðu að ganga eða hjóla frá Seltjarnarnesi","body":""},{"level":"info","title":"Styttri heilmyrkvi (~1m 6s) en á vestlægari stöðum — íhugaðu akstur til Reykjaness fyrir ~1m 40s","body":""}]'::jsonb
    ),
    (
      'hellissandur-village', 'is',
      'Hellissandur',
      'Vestasta þorpið á Snæfellsnesi, við rætur Snæfellsjökuls. Opnar útsýnisleiðir til norðurs og vesturs frá útjöðrum þorpsins. Gamla útvarpsstöðin nálægt er kennileiti á svæðinu.',
      'Frí bílastæði í þorpsmiðju og nálægt gömlu útvarpsstönginni.',
      'Sléttur jarðvegur með opnu útsýni. Skjólstýrður frá sunnanvindum af Snæfellsjökli.',
      '[{"level":"warn","title":"Lítið þorp (~380 íbúar) — takmarkað matvöruúrval og gisting","body":""},{"level":"warn","title":"Bókaðu gistingu með góðum fyrirvara — gistirými verða uppseld vikuna fyrir sólmyrkvann","body":""}]'::jsonb
    ),
    (
      'hellnar-viewpoint', 'is',
      'Hellnar — strandútsýni',
      'Sögulegt útgerðarþorp á suðurströnd Snæfellsness, tengt Arnarstapa með frægri 2,5 km strandgönguleið. Hellnar bjóða dramatískar bergmyndanir, þar á meðal Gatkletti og strandhellinn Baðstofuna. Aðeins minna fjölmennt en Arnarstapi en með takmörkuð bílastæði.',
      'Lítið bílastæði við endann á veginum að Hellnum. Um 15 bílar. Auka bílastæði á Arnarstapa (2,5 km ganga eftir strandstígnum).',
      'Strandþorp í sjávarmáli. Suðlæg strönd með útsýni til SV/V yfir Atlantshaf. Gönguleiðir í gegnum hraun að sjávarhellum og boga.',
      '[{"level":"info","title":"Minna og rólegra en Arnarstapi — en líka með minni bílastæði","body":""},{"level":"info","title":"Fjöruhúsið kaffihús hefur takmarkaða gestamóttöku — gæti lokað snemma á sólmyrkvadegi","body":""}]'::jsonb
    ),
    (
      'hvalsneskirkja', 'is',
      'Hvalsneskirkja',
      'Söguleg steinkirkja frá 1887 á opinni suðurströnd Reykjanesskagans, í dramatískum sandöldum og hrauni með algjörlega óhindruðu útsýni til suðurs og vesturs. Skáldið Hallgrímur Pétursson þjónaði hér sem prestur. Kirkjan veitir táknræna umgjörð fyrir sólmyrkvann.',
      'Lítið frítt bílastæði við kirkjuna. Malbikaður aðkeyrsluvegur um Þjóðveg 44 frá Sandgerði.',
      'Grasi vaxinn kirkjugarður með malarstígum. Opin strandhraunbreiða með sandöldum og hraun til suðurs og vesturs — algjörlega óhindraður vestursjóndeildarhringur.',
      NULL::jsonb
    ),
    (
      'isafjordur-harbour', 'is',
      'Ísafjarðarhöfn',
      'Hafnarsléttan á Ísafirði býður upp á opinn vestursjóndeildarhring yfir mynni fjarðarins. Sem stærsti bær Vestfjarða sameinar Ísafjörður gott aðgengi við miðlæga staðsetningu á heilmyrkvaleiðinni. Umliggjandi fjöll ramma inn himininn til austurs en skilja eftir vesturátt — það mikilvægasta — algjörlega opna.',
      'Stór almenningsbílastæði á hafnarsléttunni (við Pollinn). Frí, malbikuð.',
      'Slétt uppfyllt hafnarland og malbikað kantmúr. Engar hindranir til vesturs.',
      '[{"level":"info","title":"⚠️ HÆTTA Á SJÓNDEILDARHRING: Djúpur fjörður með bröttum fjöllum — sólin gæti verið hluthuldin frá sumum stöðum","body":""},{"level":"info","title":"Bestur staður: hafnarbryggjan eða strandlína sem snýr NV að mynni fjarðarins","body":""},{"level":"info","title":"Forðastu staði inni í landi — fjöll munu hindra útsýnið frá miðbænum","body":""},{"level":"info","title":"Íhugaðu akstur til Bolungarvíkur (15 mín) fyrir opnari strandstöðu","body":""}]'::jsonb
    ),
    (
      'keflavik-asbru-viewpoint', 'is',
      'Keflavíkurflugvöllur (Ásbrú)',
      'Slétta hraunbreiðan í kringum Keflavíkurflugvöll er ein af opnustu, óhindruðustu landssvæðum Íslands. Ásbrú-svæðið býður slétta opna jörð með skýrum vestursjóndeildarhring út yfir hafið. Þar sem flestir alþjóðlegir gestir koma um KEF gæti þetta verið hentugasti sólmyrkvastaðurinn ef þú lendir á sólmyrkvadegi.',
      'Opin slétt svæði í Ásbrú-hverfinu. Frí óformleg bílastæði.',
      'Slétt hraunbreiða þakin mosa og möl. Algjörlega slétt og opið landslag.',
      '[{"level":"info","title":"Hagnýtur fremur en fagurfræðilegur staður — fyrrum herstöðvarsvæði","body":""},{"level":"info","title":"Veldu opið svæði fjarri Ásbrú-byggingum fyrir óhindrað útsýni til vesturs","body":""},{"level":"info","title":"Hentugasti staðurinn fyrir ferðamenn sem koma eða fara um Keflavíkurflugvöll","body":""}]'::jsonb
    ),
    (
      'kirkjufell-viewpoint', 'is',
      'Kirkjufell — útsýnisstaður',
      'Mest myndaða fjall Íslands gerir stórkostlegan bakgrunn fyrir sólmyrkvann. 5 mínútna ganga frá bílastæði að klassíska útsýnisstaðnum með Kirkjufellsfossi í forgrunni og hinu táknræna fjalli sem rís upp í vestri. Vandaðu staðsetninguna — Kirkjufell sjálft gæti hindrað sólina frá sumum stöðum.',
      'Stórt bílastæði við Kirkjufellsfoss. Frítt, malbikað.',
      'Vel viðhaldinn malarstígur frá bílastæði að útsýnisstað. Að mestu sléttur.',
      '[{"level":"info","title":"⚠️ ATHUGIÐ SJÓNDEILDARHRING: Kirkjufell er nálægt sólarátt — staðsettu þig á vesturhlið útsýnissvæðisins","body":""},{"level":"info","title":"Sólmyrkvamynd með Kirkjufell í baksýn væri stórbrotin, en krefst nákvæmrar staðsetningar","body":""}]'::jsonb
    ),
    (
      'latrabjarg-cliffs', 'is',
      'Látrabjarg',
      'Stærsta fuglabjarg Evrópu, 14 km langt og allt að 440 m hátt, á vestasta odda Íslands. Útsýnisstaðurinn á bjargbrúninni snýr beint í vestur yfir opið Atlantshaf án nokkurrar hindrunar á sjóndeildarhringnum. Að mörgu leyti besti sólmyrkvastaður Vestfjarða — en mjög afskekktur, krefst góðs undirbúnings.',
      'Lítið malarbílastæði við útsýnisstaðinn. Frítt.',
      'Grasi vaxin bjargbrún. Haltu þig vel fjarri ógirtum klettabrúnum. Getur verið mjög vindasamt.',
      '[{"level":"warn","title":"Mjög afskekkt: 2,5 klst akstur frá Patreksfirði um malarveg","body":""},{"level":"warn","title":"Engin þjónusta, ekkert farsímasamband, engin salerni — taktu með allt sem þú þarft","body":""},{"level":"warn","title":"Ekkert skjól fyrir vindi eða regni — klæddu þig í fullkomnar vindheldar flíkur","body":""},{"level":"bad","title":"Klettabrúnir eru ógirtar og hættulega brattar — haltu þig vel fjarri","body":""},{"level":"warn","title":"Mjög takmörkuð bílastæði (~20 bílar) — mættu snemma á sólmyrkvadegi","body":""}]'::jsonb
    ),
    (
      'londrangar-malarrif', 'is',
      'Lóndrangar / Malarrif',
      'Tveir dramatískir basaltdrangar — sá hærri 75 metrar og sá lægri 61 metri — standa eins og verðir undan suðvesturströnd Snæfellsness. Þessir eldfjallastólpar eru leifar fornra eldgosa og hluti af Snæfellsjökulsþjóðgarði. Strandstígurinn býður dramatískt útsýni og er einn af myndrænustu sólmyrkvastöðum á Íslandi.',
      'Bílastæði við Lóndrangaútsýnisstaðinn (~20 bílar) og sérstakt bílastæði við gestastofu Malarrifs (~20 bílar). Bæði í stuttri göngufjarlægð frá klettunum.',
      'Strandbjargstígur. Snýr SV og opnast í Atlantshaf. Lág hraunbreiða í landi. Gönguleiðir vel viðhaldnar.',
      '[{"level":"info","title":"Vinsæll ferðamannastaður — búast má við fjölmenni á sólmyrkvadegi","body":""},{"level":"info","title":"Klettabrúnir geta verið hálar og hættulegar — haltu þig á merktum stígum","body":""}]'::jsonb
    ),
    (
      'olafsvik-harbour', 'is',
      'Ólafsvíkurhöfn',
      'Lítill útgerðarbær á norðurströnd Snæfellsness. Hafnarsvæðið býður slétta útsýnispall með Snæfellsjökul í suðri. Opin hafsýn til norðurs og vesturs.',
      'Frí bílastæði nálægt höfninni og meðfram aðalveginum.',
      'Slétt hafnarsvæði og strandvegur. Opnar útsýnisleiðir til norðurs og vesturs.',
      '[{"level":"info","title":"Best þjónusti bærinn á norðanverðu Snæfellsnesi — matvöruverslun (Samkaup), veitingastaðir, eldsneyti","body":""},{"level":"warn","title":"Hafnarsvæðið verður líklega aðal samkomustaðurinn — mættu snemma fyrir besta stað","body":""}]'::jsonb
    ),
    (
      'ondverdarnes-svortuloft', 'is',
      'Öndverðarnes / Svörtuloft',
      'Vesturoddi Snæfellsnessins — dramatísk klettabrún þar sem svörtu basaltbjörgin Svörtuloft falla í Atlantshafið. Lítill appelsínugulur Skálasnagaviti stendur við klettabrúnina. Þessi staður liggur beint á miðlínu sólmyrkvans og býður allt að 2m 11s heilmyrkva — einn lengsti á Íslandi.',
      'Endi á holóttum malarvegi (15 mín frá Hellissandi). Lítið bílastæði fyrir um 10 bíla. Engin auka stæði. Mættu snemma á sólmyrkvadegi.',
      'Slétt klettabrún. Opið Atlantshaf til V/NV/SV. Dramatísk svört sjávarbjörg. Mjög vindasamt — einn af vindasömustu stöðum á Íslandi.',
      '[{"level":"info","title":"Mjög vindasamt — festu allan búnað og klæddu þig í vindheldar flíkur","body":""},{"level":"info","title":"Aðgengi um malarveg (15 mín frá Hellissandi) — aktu hægt","body":""},{"level":"info","title":"Mjög takmörkuð bílastæði (~10 bílar) — mættu snemma","body":""},{"level":"info","title":"Engin þjónusta, ekkert farsímasamband, ekkert skjól — taktu með allt sem þú þarft","body":""},{"level":"info","title":"Klettabrúnir eru ógirtar og hættulega brattar","body":""}]'::jsonb
    ),
    (
      'patreksfjordur-beach', 'is',
      'Patreksfjarðarströnd',
      'Patreksfjörður er við ytra svæði Vestfjarða með frábæru aðgengi um Þjóðveg 62. Ströndin býður slétt sandflæmi þar sem fjarðarmunnurinn opnast til vestursuðvesturs. Bærinn hefur eldsneytisstöð og grunnþjónustu, sem gerir hann að hagnýtri bækistöð fyrir sólmyrkvagesti.',
      'Götubílastæði um bæinn eru frí. Slétt grasflöt nálægt höfninni fyrir óformlegt útsýni.',
      'Sandströnd og slétt hafnarsvæði. Vesturútsýni yfir fjörðinn óhindrað.',
      '[{"level":"info","title":"⚠️ HÆTTA Á SJÓNDEILDARHRING: Fjöll geta hindrað sólina að hluta frá sumum stöðum í bænum","body":""},{"level":"info","title":"Staðsettu þig á vesturströnd fjarðarins fyrir besta sjónarhorn","body":""},{"level":"info","title":"Ef sólin er hindruð frá þínum stað, aktu til Breiðavíkur (1 klst vestur) eða Látrabjargs (2,5 klst vestur)","body":""}]'::jsonb
    ),
    (
      'perlan-reykjavik', 'is',
      'Perlan',
      'Hið táknræna glerhvelfingahús Reykjavíkur, á Öskjuhlíð fyrir ofan borgina. 360° útsýnispallurinn býður óhindrað útsýni — vestur yfir Faxaflóa að setjandi sól, norður yfir borgina og austur að Esjunni. Hækkar þig upp fyrir þaklínur Reykjavíkur og býður besta sólmyrkvasjónarhorn í borginni sjálfri.',
      'Bílastæði á Öskjuhlíð með pláss fyrir um 100 bíla. Einnig aðgengilegt með strætó og göngu/hjólastígum gegnum Öskjuhlíðarskóginn.',
      'Hækkuð staðsetning á hól (~60 m yfir sjávarmáli). Glerútsýnispallur með 360° sjónarhorni. Algjörlega óhindraður vestursjóndeildarhringur yfir hafið. Þéttbýlt umhverfi en hækkað yfir þaklínur.',
      '[{"level":"info","title":"Aðgangseyrir áskilinn (Perlan-safnsmiði)","body":""},{"level":"info","title":"Líklega selur sérstaka sólmyrkvaviðburðamiða — athugaðu á perlan.is","body":""},{"level":"info","title":"Verður mjög fjölmennt — útsýnispallurinn hefur takmarkaða gestamóttöku","body":""},{"level":"info","title":"Styttri heilmyrkvi (~1 mín) en á vestlægari stöðum","body":""},{"level":"info","title":"Bókaðu aðganginn með góðum fyrirvara","body":""}]'::jsonb
    ),
    (
      'reykjanesta-lighthouse', 'is',
      'Reykjanestáviti',
      'Suðvesturoddi Íslands með 270° hafsýn — ekkert nema opið Atlantshaf til vesturs, suðurs og norðvesturs. Hámarkar óhindrað útsýni fyrir lágstaðsetta sólmyrkvasólina. Meðal lengsti heilmyrkvi á Reykjanesi (~1m 47s).',
      'Frí malarbílastæði við vegamót Þjóðvegs 425 að vitanum. ~30 bílar.',
      'Grýtt hraunhöfði með sléttum svæðum nálægt vitanum. Mælt með góðum gönguskóm.',
      '[{"level":"bad","title":"⚠️ VIRKT ELDGOSASVÆÐI: Athugaðu eldgosastöðu á safetravel.is fyrir heimsókn","body":""},{"level":"bad","title":"Vegir að vitanum gætu verið lokaðir vegna eldgosa á Sundhnúkagígaröðinni","body":""},{"level":"warn","title":"Engin þjónusta við vitann — taktu með birgðir","body":""},{"level":"info","title":"Grýtt hraunlandslag — farðu í góðum gönguskóm","body":""}]'::jsonb
    ),
    (
      'rif-harbour-snaefellsnes', 'is',
      'Rif — höfn',
      'Útgerðarþorpið Rif á norðurströnd Snæfellsness býður opna hafsýn til norðvesturs frá hafnarsléttunni. Snæfellsjökull rís í suðri sem dramatískur bakgrunnur. Innan við 5 mínútna akstri frá Hellissandi og helstu sólmyrkvastöðum á vesturodda Snæfellsness.',
      'Slétt malarbílastæði á hafnarsvæðinu með nóg pláss. Frítt.',
      'Slétt malarbryggja og opin jörð. Þétt möl og steypa.',
      '[{"level":"warn","title":"Mjög lítið þorp (~100 íbúar) — afar takmörkuð gisting","body":""},{"level":"info","title":"Frystihúsið (The Freezer Hostel) gæti haldið sólmyrkvaviðburði — athugaðu fyrirfram","body":""}]'::jsonb
    ),
    (
      'saxholl-crater', 'is',
      'Saxhóll',
      'Gjallgígur með vel viðhaldnum málmstiga (~400 þrep) sem leiðir upp á barminn. 360° víðsýni frá toppnum nær yfir Snæfellsjökul, Atlantshafið og umliggjandi hraunbreiður. Hækkun (~110 m) hjálpar til að lyfta sjóndeildarhringnum og getur einnig veitt einstakt sjónarhorn á 360° sólarlagsáhrifin sem heilmyrkvinn skapar.',
      'Malarbílastæði við rætur gígsins. Frítt.',
      'Málmstigi upp á barminn vel viðhaldinn. Getur verið vindasamt á toppnum.',
      '[{"level":"warn","title":"Mjög vindasamt á gígbarminum — festu allan búnað og myndavélar","body":""},{"level":"warn","title":"Mjög takmörkuð bílastæði (~15 bílar við gígrót) — mættu snemma","body":""},{"level":"warn","title":"Málmstiginn (~400 þrep) getur verið hál þegar blautt","body":""},{"level":"info","title":"Ekkert skjól eða þjónusta við gíginn","body":""}]'::jsonb
    ),
    (
      'sky-lagoon', 'is',
      'Sky Lagoon',
      'Nýtísku jarðhitaspaa með óendalegri laug á vestjaðri höfuðborgarsvæðisins, sérstaklega hannað með hafsnúandi óendalegri brún sem snýr að Faxaflóa í vestur. Hönnunin liggur vel að sólmyrkvann — gestir geta upplifað hann úr lauginni með óhindruðu vestursjóndeildarhring. Aðgengilegra en Bláa lónið frá miðborg Reykjavíkur.',
      'Vandað bílastæði við Sky Lagoon. Nóg pláss. Einnig aðgengilegt með almenningsstrætó frá miðborg Reykjavíkur.',
      'Hafsnúandi aðstaða í sjávarmáli. Brún óendalegrar laugar snýr beint í vestur yfir Faxaflóa. Algjörlega óhindraður vestursjóndeildarhringur.',
      '[{"level":"info","title":"MIÐAR NAUÐSYNLEGIR — Sky Lagoon krefst fyrirframbókaðrar aðgöngu","body":""},{"level":"info","title":"Líklega selur sérstaka sólmyrkvaviðburðamiða — athugaðu á skylagoon.com","body":""},{"level":"info","title":"Mjög takmörkuð gestamóttöku — bókaðu mjög snemma","body":""},{"level":"info","title":"Stysti heilmyrkvi á listanum okkar (~58s) — þú skiptir lengd fyrir einstaka upplifun","body":""},{"level":"info","title":"Búast má við hærra verðlagi á sólmyrkvaviðburðinum","body":""}]'::jsonb
    ),
    (
      'snaefellsjokull-summit', 'is',
      'Snæfellsjökull — toppur',
      'Hið táknræna 1.446 m jökulhetta lagða eldfjall úr ferð Jules Verne að miðju jarðar. Toppurinn býður hæsta sjónarhornið á Snæfellsnesi með 360° útsýni. MIKILVÆGT: Krefst leiðsöguferðar á jökul með brodda og ísxa. Aðeins fyrir reynda fjallgöngufólk.',
      'Bílastæði við endann á F570-veginum nálægt jökuljaðri. 4WD nauðsynlegt.',
      'Aðferð að jökli yfir ís og snjó. Sprungnahætta. Leiðsögumaður nauðsynlegur.',
      '[{"level":"bad","title":"⚠️ AÐEINS FYRIR REYNDA FJALLGÖNGUFÓLK: Krefst leiðsögu með brodda og ísxa","body":""},{"level":"bad","title":"5–8 klst hringferð — verður að byrja mjög snemma til að ná toppinum fyrir sólmyrkvann (17:45 UTC)","body":""},{"level":"bad","title":"Skýjahætta er HÆRRI í 1.446 m hæð en í sjávarmáli — þú gætir gengið inn í þoku og misst af sólmyrkvanum","body":""},{"level":"bad","title":"Veður mjög óútreiknanlegt í toppshæð — vindur, lágt hitastig, hvítblinda möguleg","body":""},{"level":"warn","title":"Leiðsöguferðir á jökul verður að bóka með góðum fyrirvara","body":""}]'::jsonb
    ),
    (
      'stykkisholmur-harbour-hill', 'is',
      'Stykkishólmur — hafnarhæðin',
      'Stærsti bær á Snæfellsnesi, við Breiðafjörð. Klettahæðin Súgandisey býður 360° útsýni, þar á meðal skýrt vestursjóndeildarhring yfir eyjadreifðan flóann. Frábær þjónusta og gisting gera Stykkishólm að besta þéttbýla sólmyrkvabækistöðinni á svæðinu.',
      'Bílastæði í miðbænum eru frí. Bílastæði við höfnina með göngu að Súgandisey.',
      'Klettahæð úr basalti (~20 m) með stigum. Slétt útsýnispall á toppnum. Höfnin neðan við er fullkomlega malbikuð.',
      '[{"level":"info","title":"Best þjónusti bærinn á Snæfellsnesi — hótel, veitingastaðir, matvörur, Baldur-ferja","body":""},{"level":"info","title":"Styttri heilmyrkvi en á vestlægari stöðum á Snæfellsnesi — viðskipti er framúrskarandi þjónusta","body":""},{"level":"info","title":"Gakk upp á Súgandisey fyrir besta hækkaða útsýnisstaðinn","body":""}]'::jsonb
    ),
    (
      'svodufoss-waterfall', 'is',
      'Svöðufoss',
      'Myndrænn 10 metra foss sem fellur yfir stórbrotna stuðlabergsbjargi á norðurhlið Snæfellsness. Sérstaklega mælt með af eclipse2026.is sem tilvalinn forgrunn fyrir sólmyrkvaljósmyndun. Stór steypuverk + ægileg jarðfræði + stutt heilmyrkva = einstök sólmyrkvasamsetning.',
      'Lítið hliðarstæði meðfram veginum. Um 10 bílar. Auðvelt að missa af — leitaðu að litlu skilti.',
      'Stutt ganga frá veginum að útsýnisstaðnum við fossinn. Slétt til lítillega hallandi. Útsýnissvæðið er með opnu útsýni til vesturs yfir akrana og að ströndinni.',
      '[{"level":"info","title":"Mjög takmörkuð bílastæði — mættu snemma eða gakktu frá Ólafsvík","body":""},{"level":"info","title":"Engin þjónusta við fossinn","body":""},{"level":"info","title":"Fossinn sjálfur er lítill (10 m) — aðdráttaraflið er stuðlabergsbjargi á bak við hann","body":""}]'::jsonb
    ),
    (
      'ytri-tunga-beach', 'is',
      'Ytri Tunga',
      'Einn besti staðurinn á Íslandi til að sjá selalegur — selir liggja reglulega á klettum rétt undan landi, sérstaklega á sumrin. Ólíkt flestum íslenskum ströndum hefur Ytri Tunga gulleitan sand frekar en svartan, sem skapar mjúkt og litríkt forgrunn fyrir sólmyrkvaljósmyndir með dramatísku himinhvelfingunni.',
      'Lítið bílastæði við aðgangsstaðinn að ströndinni. Um 15 bílar. Stutt ganga niður á ströndina.',
      'Slétt gulleit sandströnd á suðurströnd. Opið útsýni til V/SV yfir Faxaflóa. Lágt landslag, engar hindranir.',
      '[{"level":"info","title":"Styttri heilmyrkvi (~1m 25s) en á norðanverðu Snæfellsnesi","body":""},{"level":"info","title":"Haltu fjarlægð frá selum — ekki nálgast eða raska þeim (íslensk lög)","body":""},{"level":"info","title":"Engin þjónusta við ströndina","body":""}]'::jsonb
    )
)
INSERT INTO viewing_spot_translations (
  spot_slug, locale, name, description, parking_info, terrain_notes, warnings
)
SELECT t.spot_slug, t.locale, t.name, t.description, t.parking_info, t.terrain_notes, t.warnings
FROM translations t
WHERE EXISTS (SELECT 1 FROM viewing_spots vs WHERE vs.slug = t.spot_slug)
ON CONFLICT (spot_slug, locale) DO UPDATE SET
  name          = EXCLUDED.name,
  description   = EXCLUDED.description,
  parking_info  = EXCLUDED.parking_info,
  terrain_notes = EXCLUDED.terrain_notes,
  warnings      = EXCLUDED.warnings,
  updated_at    = NOW();
