/**
 * Pre-computed eclipse-grid loader + nearest-point lookup.
 *
 * The grid (`public/eclipse-data/grid.json`, ~600 points, ~120 KB) is
 * generated by `scripts/compute-eclipse-grid.py` and contains per-point
 * eclipse geometry: totality_start (C2), totality_end (C3), c1, c4,
 * sun altitude/azimuth, duration_seconds.
 *
 * Used by `/api/spots/[slug]` to enrich each spot with the four contact
 * times (C1/C2/C3/C4) at the spot's coordinates.
 */
import { readFileSync } from 'node:fs'
import { resolve, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

export interface EclipseGridPoint {
  lat: number
  lng: number
  sun_altitude: number
  sun_azimuth: number
  totality_start: string | null
  totality_end: string | null
  duration_seconds: number
  /** Partial begins (UTC ISO). May be missing on grids generated before
   *  the C1/C4 bisection pass was added — callers must handle null. */
  c1?: string | null
  /** Partial ends (UTC ISO). Same caveat as c1. */
  c4?: string | null
}

interface RawEclipseGrid {
  eclipse_date: string
  generated: string
  total_points: number
  in_totality: number
  points: EclipseGridPoint[]
}

let cache: RawEclipseGrid | null = null
let loadPromise: Promise<RawEclipseGrid> | null = null

function loadFromFilesystem(): RawEclipseGrid | null {
  const candidates = [
    resolve(process.cwd(), 'public', 'eclipse-data', 'grid.json'),
    resolve(process.cwd(), '.output', 'public', 'eclipse-data', 'grid.json'),
  ]
  try {
    const currentDir = dirname(fileURLToPath(import.meta.url))
    candidates.push(resolve(currentDir, '..', '..', 'public', 'eclipse-data', 'grid.json'))
    candidates.push(resolve(currentDir, '..', '..', '..', 'public', 'eclipse-data', 'grid.json'))
  } catch { /* import.meta.url may not resolve in all envs */ }

  for (const path of candidates) {
    try {
      const grid = JSON.parse(readFileSync(path, 'utf-8')) as RawEclipseGrid
      console.log(`[Eclipse] Loaded grid from filesystem: ${path} (${grid.total_points} points)`)
      return grid
    } catch { /* try next */ }
  }
  return null
}

async function loadRaw(): Promise<RawEclipseGrid> {
  const fromFS = loadFromFilesystem()
  if (fromFS) return fromFS

  // Nitro serverAssets storage (Vercel-bundled fallback)
  try {
    const data = await useStorage('assets:server:eclipse-data').getItem('grid.json')
    if (data) {
      const grid = (typeof data === 'string' ? JSON.parse(data) : data) as RawEclipseGrid
      console.log(`[Eclipse] Loaded grid via Nitro storage (${grid.total_points} points)`)
      return grid
    }
  } catch (e: any) {
    console.warn('[Eclipse] Nitro storage fallback failed:', e.message)
  }

  // Last resort: fetch from own public URL (static assets on CDN)
  try {
    const config = useRuntimeConfig()
    const baseUrl = config.public.siteUrl
      || (process.env.VERCEL_URL ? `https://${process.env.VERCEL_URL}` : '')
      || 'http://localhost:3000'
    const url = `${baseUrl}/eclipse-data/grid.json`
    console.log(`[Eclipse] Attempting HTTP fetch from ${url}`)
    const res = await fetch(url)
    if (res.ok) {
      const grid = await res.json() as RawEclipseGrid
      console.log(`[Eclipse] Loaded grid via HTTP (${grid.total_points} points)`)
      return grid
    }
    console.error(`[Eclipse] HTTP fetch failed with status ${res.status}`)
  } catch (e: any) {
    console.error('[Eclipse] HTTP fallback failed:', e.message)
  }

  throw new Error('[Eclipse] Could not load grid.json from any source')
}

export async function loadEclipseGrid(): Promise<RawEclipseGrid> {
  if (cache) return cache
  if (loadPromise) return loadPromise
  loadPromise = (async () => {
    const grid = await loadRaw()
    cache = grid
    loadPromise = null
    return grid
  })()
  return loadPromise
}

/**
 * Find the grid point closest to (lat, lng), optionally restricted to
 * points inside the totality path (i.e. with a non-null totality_start).
 * Uses cos-scaled squared-Euclidean distance — same shape as haversine
 * for ranking, no trig.
 */
export async function nearestGridPoint(
  lat: number,
  lng: number,
  options: { onlyInTotality?: boolean } = {},
): Promise<EclipseGridPoint | null> {
  const grid = await loadEclipseGrid()
  const cosLat = Math.cos((lat * Math.PI) / 180)

  let best: EclipseGridPoint | null = null
  let bestDist = Infinity

  for (const p of grid.points) {
    if (options.onlyInTotality && p.totality_start == null) continue
    const dLat = p.lat - lat
    const dLng = (p.lng - lng) * cosLat
    const d = dLat * dLat + dLng * dLng
    if (d < bestDist) {
      bestDist = d
      best = p
    }
  }
  return best
}
