/**
 * Frozen viewing-spot archive.
 *
 * The Aug 12 2026 eclipse has passed, so this data will never change
 * again. It is imported statically (not read from disk) so Nitro bundles
 * it into the server build — that removes both the Supabase runtime
 * dependency and any filesystem path assumptions on Vercel.
 *
 * This module is the ONLY place that knows the archive's on-disk shape.
 * Generated by scripts/snapshot-archive.mjs.
 */
import spotsData from '../data/archive/spots.json'
import translationsData from '../data/archive/spot-translations.json'

export interface ArchivedSpot {
  id: string
  name: string
  slug: string
  lat: number
  lng: number
  region: string
  totality_duration_seconds: number | null
  [key: string]: unknown
}

interface ArchivedTranslation {
  spot_slug: string
  locale: string
  name: string | null
  description: string | null
  parking_info: string | null
  terrain_notes: string | null
  warnings: unknown
}

const TRANSLATABLE_FIELDS = [
  'name',
  'description',
  'parking_info',
  'terrain_notes',
  'warnings',
] as const

const SPOTS = (spotsData as { spots: ArchivedSpot[] }).spots
const TRANSLATIONS = (translationsData as { translations: ArchivedTranslation[] }).translations

/** locale -> slug -> translation row */
const byLocale = new Map<string, Map<string, ArchivedTranslation>>()
for (const tr of TRANSLATIONS) {
  let forLocale = byLocale.get(tr.locale)
  if (!forLocale) {
    forLocale = new Map()
    byLocale.set(tr.locale, forLocale)
  }
  forLocale.set(tr.spot_slug, tr)
}

/**
 * Overlay locale copy onto a spot. Any NULL field on the translation row
 * falls back to the English base row, so partial translations are safe.
 * Always returns a fresh object — callers must never be able to mutate
 * the module-level archive.
 */
function localise(spot: ArchivedSpot, locale: string): ArchivedSpot {
  const copy = { ...spot }
  if (locale === 'en') return copy
  const tr = byLocale.get(locale)?.get(spot.slug)
  if (!tr) return copy
  for (const field of TRANSLATABLE_FIELDS) {
    const value = (tr as Record<string, unknown>)[field]
    if (value !== null && value !== undefined) copy[field] = value
  }
  return copy
}

/** Every spot, longest totality first (the order the list page expects). */
export function getAllSpots(locale = 'en'): ArchivedSpot[] {
  return SPOTS.map(s => localise(s, locale))
}

export function getSpotBySlug(slug: string, locale = 'en'): ArchivedSpot | null {
  const spot = SPOTS.find(s => s.slug === slug)
  return spot ? localise(spot, locale) : null
}

export function getSpotSlugs(): string[] {
  return SPOTS.map(s => s.slug)
}
