/**
 * Frozen eclipse-day weather archive.
 *
 * THIS IS HISTORICAL DATA, NEVER LIVE. Every reading here is a vedur.is
 * HARMONIE-AROME forecast slot valid on 2026-08-12 (UTC), captured from
 * `weather_forecasts` on 2026-08-13 just before the ingest crons were
 * stopped. Nothing in this module talks to Supabase, vedur.is, or any
 * other network service — the archive must keep serving with no database
 * at all.
 *
 * It is imported statically (not read from disk) so Nitro bundles it into
 * the server build, exactly like server/utils/spotsArchive.ts — which is
 * the reference implementation this module follows, including the rule
 * that every accessor returns defensive copies so callers can never
 * mutate the module-level archive.
 *
 * Generated by scripts/snapshot-archive.mjs.
 */
import weatherData from '../data/archive/eclipse-day-weather.json'
import { ECLIPSE_INSTANT, ECLIPSE_FORECAST_TOLERANCE_MS, pickNearestForecastRow } from './vedur'

export interface ArchivedStation {
  id: string
  name: string
  lat: number
  lng: number
  region: string | null
}

/** One hourly forecast slot, in the shape the client components expect. */
export interface ArchivedSlot {
  valid_time: string
  cloud_cover: number | null
  precip_prob: number | null
}

export interface ArchivedTimeline extends ArchivedStation {
  forecasts: ArchivedSlot[]
}

export interface TotalityReading {
  station_id: string
  cloud_cover: number | null
  forecast_valid_at: string | null
}

interface RawForecast {
  station_id: string
  forecast_time: string
  valid_time: string
  cloud_cover: number | null
  precipitation_prob: number | null
}

interface RawArchive {
  snapshot_of: string
  eclipse_date: string
  captured_at: string
  stations: ArchivedStation[]
  forecasts: RawForecast[]
}

const ARCHIVE = weatherData as unknown as RawArchive

/** The UTC calendar day every archived slot belongs to ('2026-08-12'). */
export const ECLIPSE_DAY = ARCHIVE.eclipse_date

/**
 * When the snapshot was taken. Endpoints report this as `fetched_at` so
 * the payload still carries an honest provenance timestamp — it is the
 * moment the data was frozen, not the moment of the request.
 */
export const CAPTURED_AT = ARCHIVE.captured_at

// Stations, ordered by region then id — the order the old
// `.order('region')` Supabase read produced.
const STATIONS: ArchivedStation[] = [...ARCHIVE.stations].sort((a, b) => {
  const ra = a.region ?? ''
  const rb = b.region ?? ''
  if (ra !== rb) return ra < rb ? -1 : 1
  return a.id < b.id ? -1 : a.id > b.id ? 1 : 0
})

const STATION_BY_ID = new Map(STATIONS.map(s => [s.id, s]))

/**
 * Collapse the raw rows to one slot per (station, valid_time), keeping the
 * freshest vedur batch — the snapshot contains 12 overlapping
 * `forecast_time` batches, and emitting all of them would repeat every
 * hour a dozen times. This mirrors the de-duplication the live
 * forecast-timeline endpoint did in SQL + JS.
 */
const TIMELINES = (() => {
  const byStation = new Map<string, Map<string, { batch: string; slot: ArchivedSlot }>>()

  for (const row of ARCHIVE.forecasts) {
    if (!row.station_id || !row.valid_time) continue
    let slots = byStation.get(row.station_id)
    if (!slots) {
      slots = new Map()
      byStation.set(row.station_id, slots)
    }
    const existing = slots.get(row.valid_time)
    if (existing && existing.batch >= row.forecast_time) continue
    slots.set(row.valid_time, {
      batch: row.forecast_time,
      slot: {
        valid_time: row.valid_time,
        cloud_cover: row.cloud_cover,
        precip_prob: row.precipitation_prob,
      },
    })
  }

  const result = new Map<string, ArchivedSlot[]>()
  for (const [stationId, slots] of byStation) {
    const ordered = Array.from(slots.values())
      .sort((a, b) => (a.slot.valid_time < b.slot.valid_time ? -1 : a.slot.valid_time > b.slot.valid_time ? 1 : 0))
      .map(entry => entry.slot)
    result.set(stationId, ordered)
  }
  return result
})()

/**
 * The reading nearest to the eclipse instant for each station — i.e. what
 * the sky was forecast to be doing at totality. Hourly slots put this in
 * the 17:00–18:00Z window everywhere along the path.
 */
const TOTALITY_READINGS: TotalityReading[] = (() => {
  const eclipseMs = ECLIPSE_INSTANT.getTime()
  const rows: TotalityReading[] = []
  for (const station of STATIONS) {
    const slots = TIMELINES.get(station.id)
    if (!slots?.length) continue
    const picked = pickNearestForecastRow(slots, eclipseMs, ECLIPSE_FORECAST_TOLERANCE_MS)
    if (!picked) continue
    rows.push({
      station_id: station.id,
      cloud_cover: picked.cloud_cover,
      forecast_valid_at: picked.valid_time,
    })
  }
  return rows
})()

/** Every archived station, ordered by region. */
export function getAllStations(): ArchivedStation[] {
  return STATIONS.map(s => ({ ...s }))
}

export function getStation(id: string): ArchivedStation | null {
  const station = STATION_BY_ID.get(id)
  return station ? { ...station } : null
}

/** Eclipse-day hourly slots for one station, ascending. `[]` if unknown. */
export function getStationTimeline(id: string): ArchivedSlot[] {
  const slots = TIMELINES.get(id)
  return slots ? slots.map(s => ({ ...s })) : []
}

/** Station metadata joined onto its timeline; stations with no rows are omitted. */
export function getAllTimelines(): ArchivedTimeline[] {
  const out: ArchivedTimeline[] = []
  for (const station of STATIONS) {
    const slots = TIMELINES.get(station.id)
    if (!slots?.length) continue
    out.push({ ...station, forecasts: slots.map(s => ({ ...s })) })
  }
  return out
}

/** Cloud cover at totality, per station. */
export function getTotalityCloudCover(): TotalityReading[] {
  return TOTALITY_READINGS.map(r => ({ ...r }))
}

/**
 * Narrow an eclipse-day timeline to an `hours`-wide window centred on the
 * eclipse instant, clamped to what the archive actually holds.
 *
 * The live endpoint served a rolling now→now+`hours` window; the archive
 * only covers a single 24 h day, so a rolling window is meaningless. We
 * centre on totality instead: `hours=12` yields roughly midday→midnight
 * around C2, and any `hours` at or above the archived span (24) returns
 * the whole day. Slots are never interpolated, padded or extrapolated —
 * a narrower window simply returns fewer real slots.
 */
export function windowAroundTotality(slots: ArchivedSlot[], hours: number): ArchivedSlot[] {
  if (!slots.length) return []
  const halfMs = (hours / 2) * 60 * 60 * 1000
  const startMs = ECLIPSE_INSTANT.getTime() - halfMs
  const endMs = ECLIPSE_INSTANT.getTime() + halfMs
  return slots
    .filter((slot) => {
      const ts = Date.parse(slot.valid_time)
      if (Number.isNaN(ts)) return false
      return ts >= startMs && ts <= endMs
    })
    .map(s => ({ ...s }))
}
